### ISSUE TITLE
First line in dbus.nim prevents cross compiling

### ISSUE THREAD

**Issue by janflyborg** [zielmicha/nim-dbus#22]
As far as I can see, the line: 

`{.passl: "-ldbus-1".}`

in dbus.nim is unnecessary, since the library is loaded by dlopen. When cross compiling this library for another machine architecture, it forces us to have the DBus library available for that platform. 

I have removed it from my installation and everything works fine, so could it please be removed?

**Comment by janflyborg** [comment]
Anyone out there?

**Comment by aguspiza** [comment]
I just forked the repo from a fork that has done a fix ... zielmicha is not taking care of this one, try with SolitudeSF one

**Comment by zielmicha** [comment]
Yep, I don't maintain this repo anymore, but I generally merge PR that are reasonable (if I don't miss them :) ). I'm also happy to update README to redirect to some better fork.

**Comment by janflyborg** [comment]
Thanks for this and a merry Christmas.
